import NavLayout from "../../components/Layouts/NavLayout";
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { Carousel } from "react-responsive-carousel";
import Image from "next/image";
import Head from "next/head";
import { Location, Timer } from "@carbon/icons-react";
import Button from "../../components/Button";

export default function Item() {
  return (
    <div className="w-full">
      <Head>
        <title>Item Name | eBarterYan Category</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className="w-full"></div> */}
      <div className="container mx-auto flex flex-col gap-4">
        <div className="flex flex-col gap-6 pt-4 pb-6 border-b border-b-gray-100 mb-4">
          <Carousel
            showThumbs={false}
            showStatus={false}
            className="-mx-4 -mt-4 w-auto"
          >
            <div className="relative w-full min-h-[200px] aspect-square">
              <Image
                src="https://res.cloudinary.com/dppgyhery/image/upload/v1631456018/samples/ecommerce/leather-bag-gray.jpg"
                layout="fill"
                objectFit="cover"
              />
            </div>
            <div className="relative w-full min-h-[200px] aspect-square">
              <Image
                src="https://res.cloudinary.com/dppgyhery/image/upload/v1631456018/samples/ecommerce/leather-bag-gray.jpg"
                layout="fill"
                objectFit="cover"
              />
            </div>
            <div className="relative w-full min-h-[200px] aspect-square">
              <Image
                src="https://res.cloudinary.com/dppgyhery/image/upload/v1631456018/samples/ecommerce/leather-bag-gray.jpg"
                layout="fill"
                objectFit="cover"
              />
            </div>
            <div className="relative w-full min-h-[200px] aspect-square">
              <Image
                src="https://res.cloudinary.com/dppgyhery/image/upload/v1631456018/samples/ecommerce/leather-bag-gray.jpg"
                layout="fill"
                objectFit="cover"
              />
            </div>
          </Carousel>
          <div className="text-gray-300 flex item-center gap-2 text-ellipsis w-full whitespace-nowrap font-display text-xs">
            <p className="underline">Category</p>
            <p>&#62;</p>
            <p className="text-black-light">Item Name</p>
          </div>
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-1 border-b border-b-gray-100 pb-6">
              <h1 className="font-semibold text-2xl">Item Name</h1>
              <div className="text-sm break-words">
                <span className="align-middle inline-block mr-1">
                  <Location size={16} />
                </span>
                <p className="inline">Pandi, Bulacan • September 17, 2022</p>
              </div>
            </div>
            <div className="flex flex-col gap-2 pb-4">
              <h2 className="font-medium text-lg">Exchange for</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Pellentesque eu tincidunt tortor aliquam nulla.
              </p>
            </div>
            <div className="flex flex-col gap-4 pb-6">
              <div className="flex items-center justify-between rounded-[10px] p-4 border border-gray-100">
                <p className="font-display font-medium">Will end in</p>
                <div className="flex items-center gap-2">
                  <Timer size={24} />
                  <p className="text-lg">7d 3h 6m</p>
                </div>
              </div>
              <div className="flex items-center justify-between rounded-[10px] p-4 border border-gray-100">
                <p className="font-display font-medium">Claiming Options</p>
              </div>
            </div>
            <Button>Offer Now</Button>
          </div>
        </div>
      </div>
    </div>
  );
}

Item.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
