import Head from "next/head";
import { ArrowLeft, Send, Image as ImageIcon } from "@carbon/icons-react";
import Image from "next/image";
import ChatContainer from "../../components/Messages/ChatContainer";
import ChatBubble from "../../components/Messages/ChatBubble";

export default function Conversation() {
  const userId = 1;
  const chats = [
    {
      id: 1,
      sender: {
        id: 1,
        name: "User Name",
        image: {
          url: "https://res.cloudinary.com/dppgyhery/image/upload/v1639759887/idiary/users/1005/xoyowlqk13x4znkcu63p.jpg",
        },
      },
      type: "text",
      content: "Hello",
    },
    {
      id: 2,
      sender: {
        id: 2,
        name: "User Name",
        image: {
          url: "https://res.cloudinary.com/dppgyhery/image/upload/v1639759887/idiary/users/1005/xoyowlqk13x4znkcu63p.jpg",
        },
      },
      type: "text",
      content: "Hello",
    },
    {
      id: 3,
      sender: {
        id: 2,
        name: "User Name",
        image: {
          url: "https://res.cloudinary.com/dppgyhery/image/upload/v1639759887/idiary/users/1005/xoyowlqk13x4znkcu63p.jpg",
        },
      },
      type: "text",
      content: "Hello",
    },
  ];

  const chatBubbles = chats.map((message, index) => {
    // console.log(message);
    let isFromUser = message.sender.id == userId ? true : false;
    if (index + 1 <= chats.length - 1) {
      if (message.sender.id == chats[index + 1].sender.id) {
        return (
          <ChatBubble
            key={index}
            isFromUser={isFromUser}
            consecutive={true}
            content={message.content}
            type={message.type}
          />
        );
      } else {
        return (
          <ChatBubble
            key={index}
            isFromUser={isFromUser}
            consecutive={false}
            content={message.content}
            userPic={message.sender.image.url}
            type={message.type}
          />
        );
      }
    } else {
      return (
        <ChatBubble
          key={index}
          isFromUser={isFromUser}
          consecutive={false}
          content={message.content}
          userPic={message.sender.image.url}
          type={message.type}
        />
      );
    }
  });

  return (
    <div className="grid h-screen max-h-screen w-full grid-cols-1 grid-rows-[auto_1fr_auto]">
      <Head>
        <title>Messages | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav
        className="container mx-auto flex items-center justify-between gap-2 border-b
      border-gray-100 py-4"
      >
        <button>
          <ArrowLeft size={32} />
        </button>
        <div className="flex flex-row-reverse items-center gap-3">
          <div className="relative h-[36px] w-[36px] flex-shrink-0">
            <Image
              src="https://res.cloudinary.com/dppgyhery/image/upload/v1639759887/idiary/users/1005/xoyowlqk13x4znkcu63p.jpg"
              layout="fill"
              className="rounded-full"
            />
            <span
              className="absolute right-0 z-10 h-[12px] w-[12px] 
        rounded-full border-[2px] border-white bg-green-400"
            ></span>
          </div>
          <p>Other User</p>
        </div>
      </nav>
      <div className="container">
        <ChatContainer>{chatBubbles}</ChatContainer>
      </div>
      <div className="container mx-auto flex items-end gap-3 border-t border-gray-100 py-3">
        <button className="h-[50px] text-green-500">
          <ImageIcon size={32} />
        </button>
        <div
          className="max-h-[100px] w-full overflow-y-auto break-all rounded-[10px] bg-gray-100/30 bg-white
            p-3 font-body placeholder-gray-100 focus:outline-none"
          // ref={textBoxRef}
          contentEditable="true"
          // onInput={}
          suppressContentEditableWarning="true"
          role="textbox"
          placeholder="Enter message here"
        ></div>
        <button className="h-[50px] text-green-500">
          <Send size={32} />
        </button>
      </div>
    </div>
  );
}
