import { NavLayout } from "../../components/Layouts";
import Head from "next/head";
import {
  Conversation,
  MessageList,
  MessageSearchBox,
} from "../../components/Messages";
import useUiSizesStore from "../../store/useUiSizesStore";
import useMessagesStore from "../../store/useMessagesStore";

export default function Messages() {
  const { navbarHeight } = useUiSizesStore();
  const { isPageConversationOpen } = useMessagesStore();

  return (
    <div
      className="flex h-full w-full"
      style={{ height: `calc(100vh - ${navbarHeight}px)` }}
    >
      <Head>
        <title>Messages | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container relative mx-auto flex h-[calc(100%-70px)] md:h-full">
        {/* message list */}
        <div className="relative flex w-full flex-col gap-4 border-gray-100 py-4 md:max-w-[320px] md:border-x">
          <div className="flex justify-between gap-4 md:px-4">
            <h1 className="text-2xl font-semibold">Messages</h1>
          </div>
          <div className="md:px-4">
            <MessageSearchBox />
          </div>
          <div className="custom-scrollbar -mx-4 overflow-y-auto overflow-x-hidden md:px-4">
            <MessageList isForPage />
          </div>
        </div>
        {/* convo */}
        <div
          className={`fixed top-0 left-0 z-50 h-full w-full border-gray-100 bg-white transition-transform
           duration-300 md:relative md:z-0 md:border-r lg:relative
        ${isPageConversationOpen ? "" : "translate-x-full lg:translate-x-0"}`}
        >
          <Conversation />
        </div>
      </div>
    </div>
  );
}

Messages.getLayout = function getLayout(page) {
  return (
    <NavLayout noFooter={true} noStickyNavbar={true}>
      {page}
    </NavLayout>
  );
};
