import NavLayout from "../../components/Layouts/NavLayout";
import Head from "next/head";
import MessageSearchBox from "../../components/Messages/MessageSearchBox";
import MessageList from "../../components/Messages/MessageList";
import MessageListItem from "../../components/Messages/MessageListItem";
import { OverflowMenuVertical } from "@carbon/icons-react";

export default function Messages() {
  return (
    <div className="w-full">
      <Head>
        <title>Messages | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container relative mx-auto flex flex-col gap-4 py-4">
        <div className="flex justify-between gap-4">
          <h1 className="text-2xl font-semibold">Messages</h1>
          <button>
            <OverflowMenuVertical size={24} />
          </button>
        </div>
        <MessageSearchBox />
        <MessageList>
          <MessageListItem
            photo="https://res.cloudinary.com/dppgyhery/image/upload/v1639759887/idiary/users/1005/xoyowlqk13x4znkcu63p.jpg"
            sender="Other User"
            subtitle="Other: Good work!"
          />
          <MessageListItem
            photo="https://res.cloudinary.com/dppgyhery/image/upload/v1639759887/idiary/users/1005/xoyowlqk13x4znkcu63p.jpg"
            sender="OtherLong UserName"
            subtitle="Other: Good work!"
            unread={true}
          />
          <MessageListItem
            photo="https://res.cloudinary.com/dppgyhery/image/upload/v1639759887/idiary/users/1005/xoyowlqk13x4znkcu63p.jpg"
            sender="Other User"
            subtitle="Other: Good work!"
          />
        </MessageList>
      </div>
    </div>
  );
}

Messages.getLayout = function getLayout(page) {
  return <NavLayout noFooter={true}>{page}</NavLayout>;
};
