import NavLayout from "../../components/Layouts/NavLayout";
import Head from "next/head";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import { ProfileForm } from "../../components/Forms";
import { UserProfile, Account, Pen } from "@carbon/icons-react";

export default function ProfileSettings() {
  return (
    <div className="w-full">
      <Head>
        <title>Edit Profile | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto min-h-screen">
        <div className="mx-auto flex w-full max-w-[680px] flex-col gap-1 py-4">
          <h1 className="border-b border-gray-100 py-4 text-2xl font-semibold md:py-6 md:text-3xl">
            Settings
          </h1>
          <Tabs className="grid grid-cols-1 items-start gap-4 sm:grid-cols-[auto_2fr]">
            <TabList className="mt-4 flex w-full items-start gap-4 sm:h-full sm:w-[180px] sm:flex-col sm:gap-6">
              <Tab className="tab-varying" selectedClassName="tab-active">
                <UserProfile size={24} />
                <p>Profile</p>
              </Tab>
              <Tab className="tab-varying" selectedClassName="tab-active">
                <Account size={24} />
                <p>Account</p>
              </Tab>
            </TabList>
            <div>
              <TabPanel>
                <ProfileForm />
              </TabPanel>
              <TabPanel>
                {/* <form className="flex w-full flex-col gap-4 md:py-5">
                  <InputField
                    label="Email"
                    name="email"
                    type="email"
                    placeholder="youremail@mail.com"
                    infoMessage="changing email needs revalidation"
                  />
                  <InputField
                    label="Current Password"
                    name="currentPassword"
                    type="password"
                  />
                  <InputField
                    label="New Password"
                    name="newPassword"
                    type="password"
                  />
                  <div className="mt-4">
                    <Button autoWidth={true}>Save Changes</Button>
                  </div>
                </form> */}
              </TabPanel>
            </div>
          </Tabs>
        </div>
      </div>
    </div>
  );
}

ProfileSettings.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
