import Head from "next/head";
import { NavLayout } from "../components/Layouts";
import { Logo } from "../components/Icons";

export default function About() {
  return (
    <div className="flex w-full flex-col gap-4">
      <Head>
        <title>About Us | EbarterYan Barter Items at your Town</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container relative mx-auto flex flex-col items-center gap-6 py-12">
        <Logo size={100} />
        <h1 className="font-display text-4xl font-semibold">About Us</h1>
        <div className="flex flex-col gap-4 text-center">
          <p>
            Welcome to ebarteryan, the innovative bartering system that brings a
            new level of efficiency and convenience to the age-old practice of
            trading goods and services. With ebarteryan, you can easily connect
            with a network of like-minded individuals and businesses to exchange
            what you have for what you need, without the need for cash.
          </p>
          <p>
            Our platform offers a secure and user-friendly interface that
            simplifies the process of bartering, allowing you to find potential
            trade partners, negotiate deals, and complete transactions all in
            one place. Whether you&apos;re looking to trade goods, services, or
            both, ebarteryan makes it easy to connect with others and expand
            your network.
          </p>
          <p>
            Say goodbye to the limitations of traditional bartering and hello to
            ebarteryan - where the possibilities for exchange are endless. Join
            our community today and start trading on your terms.
          </p>
        </div>
      </div>
    </div>
  );
}

About.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
