import Head from "next/head";
import { CreationLayout } from "../components/Layouts";
import { CreateListingForm } from "../components/Forms";

export default function Create() {
  return (
    <CreationLayout>
      <div className="w-full">
        <Head>
          <title>Make a Barter | Barter Items at your Town</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container mx-auto">
          <CreateListingForm />
        </div>
      </div>
    </CreationLayout>
  );
}
