import Head from "next/head";
import { CreationLayout } from "../components/Layouts";
import { CreateListingForm } from "../components/Forms";
import useCreationStore from "../store/useCreationStore";
import { useEffect } from "react";

export async function getServerSideProps(context) {
  if (context.req.headers.referer) {
    const url = new URL(context.req.headers.referer) || null;
    const path = url.pathname;
    const host = `${url.protocol}//${context.req.headers.host}`;
    return {
      props: { path, host }, // will be passed to the page component as props
    };
  }
  return {
    props: {
      path: "/",
      host:
        process.env.NODE_ENV == "production"
          ? process.env.PRODUCTION_URL
          : process.env.DEVELOPMENT_URL,
    },
  };
}

export default function Create({ path, host }) {
  const { setPath, setHost } = useCreationStore();
  useEffect(() => {
    setPath(path);
    setHost(host);
  }, []);
  return (
    <div className="w-full">
      <Head>
        <title>Make a Barter | Barter Items at your Town</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">
        <CreateListingForm />
      </div>
    </div>
  );
}
Create.getLayout = function getLayout(page) {
  return <CreationLayout>{page}</CreationLayout>;
};
