import { NavLayout } from "../components/Layouts";
import Head from "next/head";

export default function ForgotPassword() {
  return (
    <NavLayout>
      <div className="w-full">
        <Head>
          <title>Forgot Password | eBarterYan</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </NavLayout>
  );
}

// ForgotPassword.getLayout = function getLayout(page) {
//   return <NavLayout>{page}</NavLayout>;
// };
