import NavLayout from "../components/Layouts/NavLayout";
import Head from "next/head";

export default function ForgotPassword() {
  return (
    <div className="w-full">
      <Head>
        <title>Forgot Password | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

ForgotPassword.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
