import Head from "next/head";
import LocationBarterButtons from "../components/LocationBarterButtons";
import ItemCard from "../components/Cards/ItemCard";
import NavLayout from "../components/Layouts/NavLayout";
import CategoryLayout from "../components/Layouts/CategoryLayout";
import useMapStore from "../store/useMapStore";

export default function Home() {
  const { listingRegion, radius } = useMapStore();
  return (
    <div className="w-full">
      <Head>
        <title>eBarterYan | Barter Items at your Town</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LocationBarterButtons />
      <div className="container relative mx-auto">
        {listingRegion && (
          <p className="align-right py-3 text-gray-300 md:pt-8">
            Listing items from{" "}
            <span className="font-medium text-black-light">
              {listingRegion} - {radius}km
            </span>
          </p>
        )}
        <div
          className="grid grid-cols-[repeat(auto-fill,_minmax(150px,_1fr))] gap-4 pb-4 
           lg:grid-cols-[repeat(auto-fill,_minmax(250px,_1fr))] lg:gap-6 lg:py-6"
        >
          <ItemCard
            name="Product Test"
            description="A valid product description"
            offers={1}
            time="7d"
            to="/1/1"
          />
          <ItemCard
            name="Product Test"
            description="A valid product description"
            offers={1}
            time="7d"
            to="/"
          />
          <ItemCard
            name="Product Test"
            description="A valid product description a very very very long description with a story of some sort"
            offers={1}
            time="7d"
            to="/"
          />
          <ItemCard
            name="Product Test"
            description="A valid product description"
            offers={1}
            time="7d"
            to="/"
          />
          <ItemCard
            name="Product Test"
            description="A valid product description"
            offers={1}
            time="7d"
            to="/"
          />
          <ItemCard
            name="Product Test"
            description="A valid product description"
            offers={1}
            time="7d"
            to="/"
          />
          <ItemCard
            name="Product Test"
            description="A valid product description"
            offers={1}
            time="7d"
            to="/"
          />
          <ItemCard
            name="Product Test"
            description="A valid product description"
            offers={1}
            time="7d"
            to="/"
          />
          <ItemCard
            name="Product Test"
            description="A valid product description"
            offers={1}
            time="7d"
            to="/"
          />
        </div>
      </div>
    </div>
  );
}

Home.getLayout = function getLayout(page) {
  return (
    <NavLayout>
      <CategoryLayout />
      {page}
    </NavLayout>
  );
};
