import NavLayout from "../components/Layouts/NavLayout";
import Head from "next/head";
import InputField from "../components/Inputs/InputField";
import Button from "../components/Button";
import { Icon } from "@iconify/react";
import ThirdPartyButton from "../components/ThirdPartyButton";
import Link from "next/link";

export default function Login() {
  return (
    <div className="w-full">
      <Head>
        <title>Login | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto flex py-6">
        <div className="flex w-full flex-col gap-6 md:m-auto md:max-w-[480px]">
          <h1 className="mx-auto text-4xl font-semibold">Login</h1>
          <form className="flex flex-col gap-4">
            <InputField
              type="email"
              label="Email"
              placeholder="youremail@mail.com"
            />
            <div className="flex flex-col gap-2">
              <InputField type="password" label="Password" />
              <Link href="/forgotpassword">
                <a className="self-end text-sm text-green-500 hover:underline">
                  Forgot Password?
                </a>
              </Link>
            </div>
            <Button>Login</Button>
          </form>
          <div className="overflow-hidden">
            <p
              class="flex w-full flex-row bg-white before:right-2 before:m-auto 
          before:-ml-[50%] before:h-[1px] before:w-1/2 before:flex-1 
          before:bg-gray-100 before:align-middle after:left-2 after:m-auto after:-mr-[50%] 
          after:h-[1px] after:w-1/2 after:flex-1 after:bg-gray-100 after:align-middle"
            >
              or
            </p>
          </div>
          <div className="flex flex-col gap-4">
            <ThirdPartyButton
              icon={
                <Icon
                  icon="flat-color-icons:google"
                  className="h-[24px] w-[24px]"
                />
              }
              text="Login with Google"
            />
            <ThirdPartyButton
              icon={
                <Icon icon="logos:facebook" className="h-[24px] w-[24px]" />
              }
              text="Login with Facebook"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

Login.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
