import { NavLayout } from "../components/Layouts";
import Head from "next/head";
import { LoginForm } from "../components/Forms";

export default function Login() {
  return (
    <NavLayout>
      <div className="w-full">
        <Head>
          <title>Login | eBarterYan</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="container mx-auto flex py-6">
          <LoginForm />
        </div>
      </div>
    </NavLayout>
  );
}

// Login.getLayout = function getLayout(page) {
//   return <NavLayout>{page}</NavLayout>;
// };
