import Head from "next/head";
import NavLayout from "../components/Layouts/NavLayout";
import NotificationTabs from "../components/Notifications/NotificationTabs";

export default function Notifications() {
  return (
    <div className="w-full">
      <Head>
        <title>Notifications | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto flex h-screen w-full max-w-[520px] justify-center py-6">
        <NotificationTabs />
      </div>
    </div>
  );
}

Notifications.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
