import Head from "next/head";
import NavLayout from "../components/Layouts/NavLayout";

export default function Notifications() {
  return (
    <div className="w-full">
      <Head>
        <title>Notifications | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto h-screen">Notifications</div>
    </div>
  );
}

Notifications.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
