import Head from "next/head";
import NavLayout from "../components/Layouts/NavLayout";
import UserOfferList from "../components/UserOfferList";
import UserOfferListItem from "../components/UserOfferListItem";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";

export default function Offers() {
  return (
    <div className="container mx-auto w-full">
      <Head>
        <title>Offers | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full py-4">
        <h1 className="text-2xl font-semibold md:py-6 md:text-3xl">Offers</h1>
        <Tabs className="grid grid-cols-1 gap-4 sm:grid-cols-[auto_2fr]">
          <TabList className="flex w-full items-start gap-4 sm:w-[200px] sm:flex-col sm:gap-3">
            <Tab className="tab" selectedClassName="tab-active">
              <p>All</p>
            </Tab>
            <Tab className="tab" selectedClassName="tab-active">
              <p>Waiting</p>
            </Tab>
            <Tab className="tab" selectedClassName="tab-active">
              <p>Accepted</p>
            </Tab>
            <Tab className="tab" selectedClassName="tab-active">
              <p>Failed</p>
            </Tab>
          </TabList>
          <div>
            <TabPanel>
              <UserOfferList>
                <UserOfferListItem status="waiting" />
                <UserOfferListItem status="failed" />
                <UserOfferListItem status="success" />
                <UserOfferListItem status="success" />
                <UserOfferListItem status="success" />
              </UserOfferList>
            </TabPanel>
            <TabPanel></TabPanel>
            <TabPanel></TabPanel>
            <TabPanel></TabPanel>
          </div>
        </Tabs>
      </div>
    </div>
  );
}

Offers.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
