import { NavLayout } from "../components/Layouts";
import Head from "next/head";
import { SavedList, SavedListItem } from "../components/Lists";

export default function Saved() {
  return (
    <NavLayout>
      <div className="container mx-auto w-full md:max-w-[900px]">
        <Head>
          <title>Saved Items | eBarterYan</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex w-full flex-col gap-4 py-4 sm:gap-4">
          <h1
            className="border-b border-gray-100 py-4 text-2xl
          font-semibold md:py-6 md:text-3xl"
          >
            Saved
          </h1>
          <div>
            <SavedList>
              <SavedListItem
                name="Product Test"
                description="A valid product description"
                offers={1}
                time="7d"
                to="/"
              />
              <SavedListItem
                name="Product Test"
                description="A valid product description"
                offers={1}
                time="7d"
                to="/"
              />
            </SavedList>
          </div>
        </div>
      </div>
    </NavLayout>
  );
}

// Saved.getLayout = function getLayout(page) {
//   return <NavLayout>{page}</NavLayout>;
// };
