import { NavLayout } from "../components/Layouts";
import Head from "next/head";
import { InputField } from "../components/Inputs";
import { Button, ThirdPartyButton } from "../components/Buttons";
import { Icon } from "@iconify/react";
import Link from "next/link";

export default function SignUp() {
  return (
    <div className="w-full">
      <Head>
        <title>Sign Up | eBarterYan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto flex py-6">
        <div className="flex w-full flex-col gap-6 md:m-auto md:max-w-[480px]">
          <h1 className="mx-auto text-4xl font-semibold">Sign Up</h1>
          <form className="flex flex-col gap-4">
            <InputField label="First Name" placeholder="First Name" />
            <InputField label="Last Name" placeholder="Last Name" />
            <InputField
              type="email"
              label="Email"
              placeholder="youremail@mail.com"
            />
            <InputField type="password" label="Password" />
            <InputField type="password" label="Re-Enter Password" />
            <p className="text-center">
              Already have an account?{" "}
              <Link href="/login">
                <a className="font-display font-medium text-green-500 hover:underline">
                  Login
                </a>
              </Link>
            </p>
            <Button>Sign Up</Button>
          </form>
          <div className="overflow-hidden">
            <p
              className="flex w-full flex-row bg-white before:right-2 before:m-auto 
          before:-ml-[50%] before:h-[1px] before:w-1/2 before:flex-1 
          before:bg-gray-100 before:align-middle after:left-2 after:m-auto after:-mr-[50%] 
          after:h-[1px] after:w-1/2 after:flex-1 after:bg-gray-100 after:align-middle"
            >
              or
            </p>
          </div>
          <div className="flex flex-col gap-4">
            <ThirdPartyButton
              icon={
                <Icon
                  icon="flat-color-icons:google"
                  className="h-[24px] w-[24px]"
                />
              }
              text="Sign Up with Google"
            />
            <ThirdPartyButton
              icon={
                <Icon icon="logos:facebook" className="h-[24px] w-[24px]" />
              }
              text="Sign Up with Facebook"
            />
          </div>
        </div>
      </div>
    </div>
  );
}

SignUp.getLayout = function getLayout(page) {
  return <NavLayout>{page}</NavLayout>;
};
